-- ============================================================================
-- Cricket Planner — initial schema
--
-- Contains:
--   1. Better Auth tables (user / session / account / verification)
--   2. Normalized tournament schema (tournaments, teams, team_stats,
--      matches, innings)
--   3. Indexes, an updated_at trigger, and RLS lockdown
--
-- The app connects to Postgres via the Supabase *session pooler* using the
-- `postgres` role, which bypasses RLS. All access control is enforced in the
-- application layer (Better Auth session + user_id scoping in Server Actions).
-- RLS is still enabled with NO policies so the public/anon PostgREST roles
-- (publishable key) cannot read or write these tables directly — defense in
-- depth.
--
-- Better Auth section is generated by `@better-auth/cli generate` and MUST
-- match the app's auth config. Regenerate if the auth config changes.
-- ============================================================================

-- ─────────────────────────────────────────────────────────────────────────────
-- 1. Better Auth
-- ─────────────────────────────────────────────────────────────────────────────

create table "user" (
  "id" text not null primary key,
  "name" text not null,
  "email" text not null unique,
  "emailVerified" boolean not null,
  "image" text,
  "createdAt" timestamptz default current_timestamp not null,
  "updatedAt" timestamptz default current_timestamp not null
);

create table "session" (
  "id" text not null primary key,
  "expiresAt" timestamptz not null,
  "token" text not null unique,
  "createdAt" timestamptz default current_timestamp not null,
  "updatedAt" timestamptz not null,
  "ipAddress" text,
  "userAgent" text,
  "userId" text not null references "user" ("id") on delete cascade
);

create table "account" (
  "id" text not null primary key,
  "accountId" text not null,
  "providerId" text not null,
  "userId" text not null references "user" ("id") on delete cascade,
  "accessToken" text,
  "refreshToken" text,
  "idToken" text,
  "accessTokenExpiresAt" timestamptz,
  "refreshTokenExpiresAt" timestamptz,
  "scope" text,
  "password" text,
  "createdAt" timestamptz default current_timestamp not null,
  "updatedAt" timestamptz not null
);

create table "verification" (
  "id" text not null primary key,
  "identifier" text not null,
  "value" text not null,
  "expiresAt" timestamptz not null,
  "createdAt" timestamptz default current_timestamp not null,
  "updatedAt" timestamptz default current_timestamp not null
);

create index "session_userId_idx" on "session" ("userId");
create index "account_userId_idx" on "account" ("userId");
create index "verification_identifier_idx" on "verification" ("identifier");

-- ─────────────────────────────────────────────────────────────────────────────
-- 2. Tournaments (normalized)
-- ─────────────────────────────────────────────────────────────────────────────

-- Parent row: one per tournament, owned by a user.
create table public.tournaments (
  id             uuid primary key default gen_random_uuid(),
  user_id        text not null references "user" ("id") on delete cascade,
  name           text not null,
  algorithm      text not null default 'round-robin'
                   check (algorithm in ('round-robin', 'single-elimination',
                                         'double-elimination', 'triple-elimination')),
  playoff_format text not null default 'world-cup'
                   check (playoff_format in ('world-cup', 'league')),
  max_overs      integer not null default 20,
  max_wickets    integer not null default 10,
  is_generated   boolean not null default false,
  phase          text not null default 'setup'
                   check (phase in ('setup', 'round-robin', 'playoffs', 'completed')),
  -- High-level lifecycle used by the tournaments list page.
  status         text not null default 'setup'
                   check (status in ('setup', 'in_progress', 'completed')),
  winner         text,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);

-- Team roster for a tournament (names are unique within a tournament and act
-- as the natural key referenced by matches/standings).
create table public.teams (
  id            uuid primary key default gen_random_uuid(),
  tournament_id uuid not null references public.tournaments (id) on delete cascade,
  name          text not null,
  position      integer not null,
  unique (tournament_id, name)
);

-- Standings / cumulative cricket statistics, one row per team.
create table public.team_stats (
  id                     uuid primary key default gen_random_uuid(),
  tournament_id          uuid not null references public.tournaments (id) on delete cascade,
  team_name              text not null,
  matches_played         integer not null default 0,
  wins                   integer not null default 0,
  losses                 integer not null default 0,
  draws                  integer not null default 0,
  no_results             integer not null default 0,
  points                 integer not null default 0,
  total_runs_scored      integer not null default 0,
  total_balls_faced      integer not null default 0,
  total_overs_played     numeric not null default 0,
  total_runs_conceded    integer not null default 0,
  total_balls_bowled     integer not null default 0,
  total_overs_bowled     numeric not null default 0,
  batting_run_rate       numeric not null default 0,
  bowling_run_rate       numeric not null default 0,
  net_run_rate           numeric not null default 0,
  highest_score          integer,
  lowest_score           integer,
  biggest_win_opponent   text,
  biggest_win_margin     integer,
  biggest_win_margin_type text check (biggest_win_margin_type in ('runs', 'wickets')),
  unique (tournament_id, team_name)
);

-- Matches, including playoff fixtures and toss + result summary.
create table public.matches (
  id                     uuid primary key default gen_random_uuid(),
  tournament_id          uuid not null references public.tournaments (id) on delete cascade,
  -- Stable in-app match id (Match.id). Preserved so playoff wiring survives saves.
  match_key              text not null,
  match_order            integer not null,
  team1                  text not null,
  team2                  text not null,
  round                  integer not null,
  status                 text not null default 'scheduled'
                           check (status in ('scheduled', 'in-progress', 'completed', 'cancelled')),
  venue                  text,
  overs                  integer not null,
  max_wickets            integer not null,
  is_playoff             boolean not null default false,
  playoff_type           text,
  phase                  text,
  second_innings_started boolean not null default false,
  -- Toss
  toss_winner            text,
  toss_decision          text check (toss_decision in ('bat', 'bowl')),
  toss_loser             text,
  -- Result summary (per-innings detail lives in `innings`)
  result_winner          text,
  result_loser           text,
  result_is_draw         boolean,
  result_is_no_result    boolean,
  result_margin_type     text check (result_margin_type in ('runs', 'wickets')),
  result_margin          integer,
  result_match_type      text check (result_match_type in ('completed', 'abandoned', 'no-result')),
  unique (tournament_id, match_key)
);

-- One row per team innings within a match (chase / defend detail).
create table public.innings (
  id           uuid primary key default gen_random_uuid(),
  match_id     uuid not null references public.matches (id) on delete cascade,
  team_slot    text not null check (team_slot in ('team1', 'team2')),
  team_name    text not null,
  runs         integer not null default 0,
  wickets      integer not null default 0,
  overs        numeric not null default 0,
  balls_faced  integer not null default 0,
  is_all_out   boolean not null default false,
  run_rate     numeric not null default 0,
  unique (match_id, team_slot)
);

-- ─────────────────────────────────────────────────────────────────────────────
-- 3. Indexes (foreign keys + common query patterns)
-- ─────────────────────────────────────────────────────────────────────────────

create index tournaments_user_id_idx        on public.tournaments (user_id);
create index tournaments_user_status_idx     on public.tournaments (user_id, status);
create index tournaments_user_updated_idx    on public.tournaments (user_id, updated_at desc);
create index teams_tournament_id_idx         on public.teams (tournament_id);
create index team_stats_tournament_id_idx    on public.team_stats (tournament_id);
create index matches_tournament_id_idx       on public.matches (tournament_id);
create index innings_match_id_idx            on public.innings (match_id);

-- ─────────────────────────────────────────────────────────────────────────────
-- 4. updated_at trigger for tournaments
-- ─────────────────────────────────────────────────────────────────────────────

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger tournaments_set_updated_at
  before update on public.tournaments
  for each row
  execute function public.set_updated_at();

-- ─────────────────────────────────────────────────────────────────────────────
-- 5. Row Level Security — enable everywhere, add NO policies.
--    The app's privileged pooler connection bypasses RLS; the anon /
--    authenticated PostgREST roles are denied by default.
-- ─────────────────────────────────────────────────────────────────────────────

alter table "user"              enable row level security;
alter table "session"           enable row level security;
alter table "account"           enable row level security;
alter table "verification"      enable row level security;
alter table public.tournaments  enable row level security;
alter table public.teams        enable row level security;
alter table public.team_stats   enable row level security;
alter table public.matches      enable row level security;
alter table public.innings      enable row level security;
